# Generated by Django 3.1.7 on 2021-03-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msgId',
            new_name='msg_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderupdate',
            old_name='updateId',
            new_name='update_id',
        ),
    ]
